[tool.poetry]
name = "books"
version = "1.4"
description = "ML Notebooks"
authors = ["Marlon Menendez <marlon.menendezg@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
xgboost = "^1.7.2"
scikit-learn = "^1.2.0"
pandas = "^1.5.2"
numpy = "^1.24.1"
tensorflow-hub = "^0.12.0"
tensorflow-datasets = "^4.8.1"
jupyterlab = "^3.5.2"
matplotlib = "^3.6.2"
black = "^22.12.0"
flake8 = "^6.0.0"
seaborn = "^0.12.2"
transformers = "^4.25.1"
datasets = "^2.8.0"
tensorboard-plugin-profile = "^2.11.1"
statsmodels = "^0.13.5"
tensorflow-macos = "^2.11.0"
tensorflow-metal = "^0.7.1"
pylint = "^2.17.0"
pylance = "^0.3.19"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
