[tool.poetry]
name = "books"
version = "1.2"
description = "Notebooks of several Machine Learning Books"
authors = ["Marlon Menendez <44656927+mmenendezg@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
matplotlib = "^3.6.1"
xgboost = "^1.6.2"
scikit-learn = "^1.1.2"
pandas = "^1.5.1"
numpy = "^1.23.4"
tensorflow-macos = "^2.10.0"
tensorflow-metal = "^0.6.0"
jupyterlab = "^3.4.8"
torch = "^1.12.1"
torchvision = "^0.13.1"
black = "^22.10.0"
flake8 = "^5.0.4"
tensorflow-hub = "^0.12.0"
tensorflow-datasets = "^4.7.0"
seaborn = "^0.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
