[tool.poetry]
name = "books"
version = "1.2"
description = "Notebooks of several Machine Learning Books"
authors = ["Marlon Menendez <44656927+mmenendezg@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
