[tool.poetry]
name = "books"
version = "1.2"
description = "Notebooks of machine learning books"
authors = ["Marlon Menendez <44656927+mmenendezg@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
tensorflow-io-gcs-filesystem = {path = "packages/tensorflow_io_gcs_filesystem-0.27.0-cp310-cp310-macosx_12_0_arm64.whl"}
tensorflow-io = {path = "packages/tensorflow_io-0.27.0-cp310-cp310-macosx_12_0_arm64.whl"}
opencv-python = "^4.6.0.66"
opencv-python-headless = "^4.6.0.66"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
