[tool.poetry]
name = "Books"
version = "1.2.9"
description = "This project contains the notebooks for several machine learning books."
authors = ["Marlon Menendez <44656927+mmenendezg@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
xgboost = "^1.6.1"
apache-beam = "^2.40.0"
tensorflow-macos = "2.9.1"
tensorflow-metal = "^0.5.0"
matplotlib = "^3.5.2"
seaborn = "^0.11.2"
tensorflow-datasets = "^4.6.0"
transformers = "^4.20.1"
flake8 = "^4.0.1"
black = "^22.6.0"
ipykernel = "^6.15.0"
pylint = "^2.14.4"
scikit-learn = "^1.1.1"
tensorflow-hub = "^0.12.0"
jupyterlab = "^3.4.3"
scikit-image = "^0.19.3"
torch = "^1.12.0"
torchvision = "^0.13.0"
torchaudio = "^0.12.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
